// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habit.sql

package sqlc

import (
	"context"

	"encoding/json/jsontext"
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (id, user_id, habit_name, icon, input_type, input_config, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, habit_name, icon, input_type, input_config, sort_order, is_active
`

type CreateHabitParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	HabitName   string         `json:"habit_name"`
	Icon        string         `json:"icon"`
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
	SortOrder   int            `json:"sort_order"`
}

type CreateHabitRow struct {
	ID          uuid.UUID      `json:"id"`
	HabitName   string         `json:"habit_name"`
	Icon        string         `json:"icon"`
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
	SortOrder   int            `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (CreateHabitRow, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.ID,
		arg.UserID,
		arg.HabitName,
		arg.Icon,
		arg.InputType,
		arg.InputConfig,
		arg.SortOrder,
	)
	var i CreateHabitRow
	err := row.Scan(
		&i.ID,
		&i.HabitName,
		&i.Icon,
		&i.InputType,
		&i.InputConfig,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, habit_name, icon, input_type, input_config, sort_order, is_active, created_at
FROM habits
WHERE id = $1 AND user_id = $2
`

type GetHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetHabit(ctx context.Context, arg GetHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitName,
		&i.Icon,
		&i.InputType,
		&i.InputConfig,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitForValidation = `-- name: GetHabitForValidation :one
SELECT input_type, input_config FROM habits
WHERE id = $1 AND user_id = $2 AND is_active = TRUE
`

type GetHabitForValidationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetHabitForValidationRow struct {
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
}

func (q *Queries) GetHabitForValidation(ctx context.Context, arg GetHabitForValidationParams) (GetHabitForValidationRow, error) {
	row := q.db.QueryRow(ctx, getHabitForValidation, arg.ID, arg.UserID)
	var i GetHabitForValidationRow
	err := row.Scan(&i.InputType, &i.InputConfig)
	return i, err
}

const getHabits = `-- name: GetHabits :many
SELECT id, habit_name, icon, input_type, input_config, sort_order, is_active FROM habits
WHERE user_id = $1
  AND is_active = $2
ORDER BY sort_order
`

type GetHabitsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	IsActive bool      `json:"is_active"`
}

type GetHabitsRow struct {
	ID          uuid.UUID      `json:"id"`
	HabitName   string         `json:"habit_name"`
	Icon        string         `json:"icon"`
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
	SortOrder   int            `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) GetHabits(ctx context.Context, arg GetHabitsParams) ([]GetHabitsRow, error) {
	rows, err := q.db.Query(ctx, getHabits, arg.UserID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitsRow
	for rows.Next() {
		var i GetHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.HabitName,
			&i.Icon,
			&i.InputType,
			&i.InputConfig,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHabitsWithLogs = `-- name: GetUserHabitsWithLogs :many
SELECT
    h.id            AS habit_id,
    h.habit_name,
    h.icon,
    h.input_type,
    h.input_config,
    h.sort_order,
    e.entry_date,
    e.value         AS log_value
FROM habits h
LEFT JOIN daily_habit_entries e
    ON h.id = e.habit_id
    AND e.entry_date BETWEEN $1::date AND $2::date
WHERE h.user_id = $3
  AND h.is_active = TRUE
ORDER BY h.sort_order, h.id ,  e.entry_date ASC
`

type GetUserHabitsWithLogsParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	UserID  uuid.UUID   `json:"user_id"`
}

type GetUserHabitsWithLogsRow struct {
	HabitID     uuid.UUID      `json:"habit_id"`
	HabitName   string         `json:"habit_name"`
	Icon        string         `json:"icon"`
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
	SortOrder   int            `json:"sort_order"`
	EntryDate   pgtype.Date    `json:"entry_date"`
	LogValue    []byte         `json:"log_value"`
}

func (q *Queries) GetUserHabitsWithLogs(ctx context.Context, arg GetUserHabitsWithLogsParams) ([]GetUserHabitsWithLogsRow, error) {
	rows, err := q.db.Query(ctx, getUserHabitsWithLogs, arg.Column1, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserHabitsWithLogsRow
	for rows.Next() {
		var i GetUserHabitsWithLogsRow
		if err := rows.Scan(
			&i.HabitID,
			&i.HabitName,
			&i.Icon,
			&i.InputType,
			&i.InputConfig,
			&i.SortOrder,
			&i.EntryDate,
			&i.LogValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIsActiveHabit = `-- name: SetIsActiveHabit :exec
UPDATE habits SET is_active = $1
WHERE id = $2 AND user_id = $3
`

type SetIsActiveHabitParams struct {
	IsActive bool      `json:"is_active"`
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) SetIsActiveHabit(ctx context.Context, arg SetIsActiveHabitParams) error {
	_, err := q.db.Exec(ctx, setIsActiveHabit, arg.IsActive, arg.ID, arg.UserID)
	return err
}

const setUserHabitLog = `-- name: SetUserHabitLog :exec
WITH habit AS (
    SELECT id FROM habits
    WHERE id = $1 AND user_id = $2 AND is_active = TRUE
)
INSERT INTO daily_habit_entries (habit_id, entry_date, value)
SELECT id, $3::date, $4 FROM habit
    ON CONFLICT (habit_id, entry_date)
DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type SetUserHabitLogParams struct {
	ID      uuid.UUID   `json:"id"`
	UserID  uuid.UUID   `json:"user_id"`
	Column3 pgtype.Date `json:"column_3"`
	Value   []byte      `json:"value"`
}

func (q *Queries) SetUserHabitLog(ctx context.Context, arg SetUserHabitLogParams) error {
	_, err := q.db.Exec(ctx, setUserHabitLog,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.Value,
	)
	return err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits SET
    habit_name = COALESCE($3, habit_name),
    icon = COALESCE($4, icon),
    input_type = COALESCE($5, input_type),
    input_config = COALESCE($6, input_config),
    sort_order = COALESCE($7, sort_order)
WHERE id = $1 AND user_id = $2
RETURNING id, habit_name, icon, input_type, input_config, sort_order, is_active
`

type UpdateHabitParams struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	HabitName   pgtype.Text        `json:"habit_name"`
	Icon        pgtype.Text        `json:"icon"`
	InputType   NullHabitInputType `json:"input_type"`
	InputConfig []byte             `json:"input_config"`
	SortOrder   pgtype.Int4        `json:"sort_order"`
}

type UpdateHabitRow struct {
	ID          uuid.UUID      `json:"id"`
	HabitName   string         `json:"habit_name"`
	Icon        string         `json:"icon"`
	InputType   HabitInputType `json:"input_type"`
	InputConfig jsontext.Value `json:"input_config"`
	SortOrder   int            `json:"sort_order"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (UpdateHabitRow, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.ID,
		arg.UserID,
		arg.HabitName,
		arg.Icon,
		arg.InputType,
		arg.InputConfig,
		arg.SortOrder,
	)
	var i UpdateHabitRow
	err := row.Scan(
		&i.ID,
		&i.HabitName,
		&i.Icon,
		&i.InputType,
		&i.InputConfig,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}
