// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"encoding/json/jsontext"
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type HabitInputType string

const (
	HabitInputTypeCheckbox    HabitInputType = "checkbox"
	HabitInputTypeText        HabitInputType = "text"
	HabitInputTypeNumber      HabitInputType = "number"
	HabitInputTypeSelect      HabitInputType = "select"
	HabitInputTypeMultiselect HabitInputType = "multiselect"
	HabitInputTypePercent     HabitInputType = "percent"
	HabitInputTypeDate        HabitInputType = "date"
	HabitInputTypeFiles       HabitInputType = "files"
	HabitInputTypeUrl         HabitInputType = "url"
)

func (e *HabitInputType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitInputType(s)
	case string:
		*e = HabitInputType(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitInputType: %T", src)
	}
	return nil
}

type NullHabitInputType struct {
	HabitInputType HabitInputType `json:"habit_input_type"`
	Valid          bool           `json:"valid"` // Valid is true if HabitInputType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitInputType) Scan(value interface{}) error {
	if value == nil {
		ns.HabitInputType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitInputType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitInputType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitInputType), nil
}

type Tokentype string

const (
	TokentypePasswordReset     Tokentype = "password_reset"
	TokentypeEmailVerification Tokentype = "email_verification"
)

func (e *Tokentype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tokentype(s)
	case string:
		*e = Tokentype(s)
	default:
		return fmt.Errorf("unsupported scan type for Tokentype: %T", src)
	}
	return nil
}

type NullTokentype struct {
	Tokentype Tokentype `json:"tokentype"`
	Valid     bool      `json:"valid"` // Valid is true if Tokentype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokentype) Scan(value interface{}) error {
	if value == nil {
		ns.Tokentype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tokentype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokentype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tokentype), nil
}

type Account struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	Provider              string             `json:"provider"`
	AccountID             string             `json:"account_id"`
	PasswordHash          pgtype.Text        `json:"password_hash"`
	AccessToken           pgtype.Text        `json:"access_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type DailyHabitEntry struct {
	HabitID   uuid.UUID          `json:"habit_id"`
	EntryDate pgtype.Date        `json:"entry_date"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Habit struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	HabitName   string             `json:"habit_name"`
	Icon        string             `json:"icon"`
	InputType   HabitInputType     `json:"input_type"`
	InputConfig jsontext.Value     `json:"input_config"`
	SortOrder   int                `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LoginAttempt struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       pgtype.Text        `json:"email"`
	Username    pgtype.Text        `json:"username"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	Success     bool               `json:"success"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenType interface{}        `json:"token_type"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	PhoneNumber   pgtype.Text        `json:"phone_number"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Bio           pgtype.Text        `json:"bio"`
	Image         pgtype.Text        `json:"image"`
	IsActive      bool               `json:"is_active"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	Timezone      pgtype.Text        `json:"timezone"`
}
