// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package Repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentFailedAttempts = `-- name: CountRecentFailedAttempts :one
SELECT COUNT(*) FROM login_attempts
WHERE (email = $1 OR username = $1 OR ip_address = $2)
  AND success = false
  AND attempted_at > NOW() - INTERVAL '15 minutes'
`

type CountRecentFailedAttemptsParams struct {
	Email     pgtype.Text `json:"email"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAttempts, arg.Email, arg.IpAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id , user_id , provider , account_id ,password_hash, access_token ,access_token_expires_at ,  refresh_token , refresh_token_expires_at  )
VALUES ($1 , $2 , $3 , $4 , $5 , $6 , $7 , $8 , $9 )
RETURNING id, user_id, provider, account_id, password_hash, access_token, access_token_expires_at, refresh_token_expires_at, refresh_token, created_at, updated_at
`

type CreateAccountParams struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	Provider              string             `json:"provider"`
	AccountID             string             `json:"account_id"`
	PasswordHash          pgtype.Text        `json:"password_hash"`
	AccessToken           pgtype.Text        `json:"access_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AccountID,
		arg.PasswordHash,
		arg.AccessToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshToken,
		arg.RefreshTokenExpiresAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.PasswordHash,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (id,user_id,token_type,token_hash,expires_at)
VALUES ($1 , $2 , $3, $4 , $5)
RETURNING id, user_id, token_type, token_hash, expires_at, created_at
`

type CreateTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenType interface{}        `json:"token_type"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.TokenType,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenType,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users( id , username , email , email_verified , full_name, date_of_birth , last_login , timezone  )
VALUES ($1, $2, $3, $4, $5, $6 , $7 , $8)
RETURNING id, username, phone_number, full_name, email, email_verified, bio, image, is_active, last_login, created_at, updated_at, date_of_birth, timezone
`

type CreateUserParams struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	FullName      string             `json:"full_name"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	Timezone      pgtype.Text        `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.FullName,
		arg.DateOfBirth,
		arg.LastLogin,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.EmailVerified,
		&i.Bio,
		&i.Image,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DateOfBirth,
		&i.Timezone,
	)
	return i, err
}

const dailyDeleteLoginAttempts = `-- name: DailyDeleteLoginAttempts :exec

DELETE FROM login_attempts
WHERE attempted_at < NOW() - INTERVAL '24 hours'
`

// TTL CLEANUP
func (q *Queries) DailyDeleteLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dailyDeleteLoginAttempts)
	return err
}

const dailyDeleteUsersWithEmailNotVerified = `-- name: DailyDeleteUsersWithEmailNotVerified :exec
DELETE FROM users
WHERE email_verified = FALSE
AND created_at < NOW() - INTERVAL '168 hours'
`

func (q *Queries) DailyDeleteUsersWithEmailNotVerified(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dailyDeleteUsersWithEmailNotVerified)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const deleteUnusedTokensForUser = `-- name: DeleteUnusedTokensForUser :exec
DELETE FROM tokens
WHERE user_id = $1
  AND token_type = $2
`

type DeleteUnusedTokensForUserParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenType interface{} `json:"token_type"`
}

func (q *Queries) DeleteUnusedTokensForUser(ctx context.Context, arg DeleteUnusedTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteUnusedTokensForUser, arg.UserID, arg.TokenType)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, user_id, provider, account_id, password_hash, access_token, access_token_expires_at, refresh_token_expires_at, refresh_token, created_at, updated_at FROM accounts
WHERE provider = $1
AND account_id = $2
LIMIT 1
`

type GetAccountByProviderParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, arg.Provider, arg.AccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.PasswordHash,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAndUseToken = `-- name: GetAndUseToken :one
DELETE FROM tokens
WHERE token_hash = $1
  AND token_type = $2
  AND expires_at > NOW()
RETURNING user_id
`

type GetAndUseTokenParams struct {
	TokenHash string      `json:"token_hash"`
	TokenType interface{} `json:"token_type"`
}

func (q *Queries) GetAndUseToken(ctx context.Context, arg GetAndUseTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAndUseToken, arg.TokenHash, arg.TokenType)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getLatestUnusedToken = `-- name: GetLatestUnusedToken :one
SELECT id, expires_at, created_at
FROM tokens
WHERE user_id = $1
  AND token_type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestUnusedTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenType interface{} `json:"token_type"`
}

type GetLatestUnusedTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestUnusedToken(ctx context.Context, arg GetLatestUnusedTokenParams) (GetLatestUnusedTokenRow, error) {
	row := q.db.QueryRow(ctx, getLatestUnusedToken, arg.UserID, arg.TokenType)
	var i GetLatestUnusedTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, created_at
FROM sessions
WHERE token_hash = $1 AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, username, phone_number, full_name, email, email_verified, bio, image, is_active, last_login, created_at, updated_at, date_of_birth, timezone FROM users
WHERE (username = $1 OR email = $1)
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.EmailVerified,
		&i.Bio,
		&i.Image,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DateOfBirth,
		&i.Timezone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, phone_number, full_name, email, email_verified, bio, image, is_active, last_login, created_at, updated_at, date_of_birth, timezone FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.EmailVerified,
		&i.Bio,
		&i.Image,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DateOfBirth,
		&i.Timezone,
	)
	return i, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (id, user_id, email , username, ip_address, success)
VALUES ($1, $2, $3,  $4,  $5, $6)
`

type InsertLoginAttemptParams struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Email     pgtype.Text `json:"email"`
	Username  pgtype.Text `json:"username"`
	IpAddress pgtype.Text `json:"ip_address"`
	Success   bool        `json:"success"`
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Username,
		arg.IpAddress,
		arg.Success,
	)
	return err
}

const isUsernameExist = `-- name: IsUsernameExist :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE username = $1
)
`

func (q *Queries) IsUsernameExist(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameExist, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setNewPassword = `-- name: SetNewPassword :exec
UPDATE accounts SET password_hash = $1
WHERE user_id = $2
`

type SetNewPasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	UserID       uuid.UUID   `json:"user_id"`
}

func (q *Queries) SetNewPassword(ctx context.Context, arg SetNewPasswordParams) error {
	_, err := q.db.Exec(ctx, setNewPassword, arg.PasswordHash, arg.UserID)
	return err
}

const setVerifiedEmail = `-- name: SetVerifiedEmail :exec
UPDATE users SET email_verified = $1
WHERE id = $2
`

type SetVerifiedEmailParams struct {
	EmailVerified bool      `json:"email_verified"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetVerifiedEmail(ctx context.Context, arg SetVerifiedEmailParams) error {
	_, err := q.db.Exec(ctx, setVerifiedEmail, arg.EmailVerified, arg.ID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}
