// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package Repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Tokentype string

const (
	TokentypePasswordReset     Tokentype = "password_reset"
	TokentypeEmailVerification Tokentype = "email_verification"
)

func (e *Tokentype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tokentype(s)
	case string:
		*e = Tokentype(s)
	default:
		return fmt.Errorf("unsupported scan type for Tokentype: %T", src)
	}
	return nil
}

type NullTokentype struct {
	Tokentype Tokentype `json:"tokentype"`
	Valid     bool      `json:"valid"` // Valid is true if Tokentype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokentype) Scan(value interface{}) error {
	if value == nil {
		ns.Tokentype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tokentype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokentype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tokentype), nil
}

type Account struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	Provider              string             `json:"provider"`
	AccountID             string             `json:"account_id"`
	PasswordHash          pgtype.Text        `json:"password_hash"`
	AccessToken           pgtype.Text        `json:"access_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type LoginAttempt struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       pgtype.Text        `json:"email"`
	Username    pgtype.Text        `json:"username"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	Success     bool               `json:"success"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenType interface{}        `json:"token_type"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	PhoneNumber   pgtype.Text        `json:"phone_number"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Bio           pgtype.Text        `json:"bio"`
	Image         pgtype.Text        `json:"image"`
	IsActive      bool               `json:"is_active"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DateOfBirth   pgtype.Date        `json:"date_of_birth"`
	Timezone      pgtype.Text        `json:"timezone"`
}
