/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthAchievementsRouteImport } from './routes/_auth/achievements'
import { Route as AuthHabitToDosRouteImport } from './routes/_auth/habit/to-dos'
import { Route as AuthHabitPerformanceRouteImport } from './routes/_auth/habit/performance'
import { Route as AuthHabitGoalsChanlengesRouteImport } from './routes/_auth/habit/goals-chanlenges'
import { Route as AuthHabitDailyLogRouteImport } from './routes/_auth/habit/daily-log'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAchievementsRoute = AuthAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHabitToDosRoute = AuthHabitToDosRouteImport.update({
  id: '/habit/to-dos',
  path: '/habit/to-dos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHabitPerformanceRoute = AuthHabitPerformanceRouteImport.update({
  id: '/habit/performance',
  path: '/habit/performance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHabitGoalsChanlengesRoute =
  AuthHabitGoalsChanlengesRouteImport.update({
    id: '/habit/goals-chanlenges',
    path: '/habit/goals-chanlenges',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthHabitDailyLogRoute = AuthHabitDailyLogRouteImport.update({
  id: '/habit/daily-log',
  path: '/habit/daily-log',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthAchievementsRoute
  '/calendar': typeof AuthCalendarRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/habit/daily-log': typeof AuthHabitDailyLogRoute
  '/habit/goals-chanlenges': typeof AuthHabitGoalsChanlengesRoute
  '/habit/performance': typeof AuthHabitPerformanceRoute
  '/habit/to-dos': typeof AuthHabitToDosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthAchievementsRoute
  '/calendar': typeof AuthCalendarRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/habit/daily-log': typeof AuthHabitDailyLogRoute
  '/habit/goals-chanlenges': typeof AuthHabitGoalsChanlengesRoute
  '/habit/performance': typeof AuthHabitPerformanceRoute
  '/habit/to-dos': typeof AuthHabitToDosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/achievements': typeof AuthAchievementsRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/habit/daily-log': typeof AuthHabitDailyLogRoute
  '/_auth/habit/goals-chanlenges': typeof AuthHabitGoalsChanlengesRoute
  '/_auth/habit/performance': typeof AuthHabitPerformanceRoute
  '/_auth/habit/to-dos': typeof AuthHabitToDosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/habit/daily-log'
    | '/habit/goals-chanlenges'
    | '/habit/performance'
    | '/habit/to-dos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/habit/daily-log'
    | '/habit/goals-chanlenges'
    | '/habit/performance'
    | '/habit/to-dos'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_auth/achievements'
    | '/_auth/calendar'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_auth/habit/daily-log'
    | '/_auth/habit/goals-chanlenges'
    | '/_auth/habit/performance'
    | '/_auth/habit/to-dos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/achievements': {
      id: '/_auth/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthAchievementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habit/to-dos': {
      id: '/_auth/habit/to-dos'
      path: '/habit/to-dos'
      fullPath: '/habit/to-dos'
      preLoaderRoute: typeof AuthHabitToDosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habit/performance': {
      id: '/_auth/habit/performance'
      path: '/habit/performance'
      fullPath: '/habit/performance'
      preLoaderRoute: typeof AuthHabitPerformanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habit/goals-chanlenges': {
      id: '/_auth/habit/goals-chanlenges'
      path: '/habit/goals-chanlenges'
      fullPath: '/habit/goals-chanlenges'
      preLoaderRoute: typeof AuthHabitGoalsChanlengesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habit/daily-log': {
      id: '/_auth/habit/daily-log'
      path: '/habit/daily-log'
      fullPath: '/habit/daily-log'
      preLoaderRoute: typeof AuthHabitDailyLogRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAchievementsRoute: typeof AuthAchievementsRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthHabitDailyLogRoute: typeof AuthHabitDailyLogRoute
  AuthHabitGoalsChanlengesRoute: typeof AuthHabitGoalsChanlengesRoute
  AuthHabitPerformanceRoute: typeof AuthHabitPerformanceRoute
  AuthHabitToDosRoute: typeof AuthHabitToDosRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAchievementsRoute: AuthAchievementsRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthHabitDailyLogRoute: AuthHabitDailyLogRoute,
  AuthHabitGoalsChanlengesRoute: AuthHabitGoalsChanlengesRoute,
  AuthHabitPerformanceRoute: AuthHabitPerformanceRoute,
  AuthHabitToDosRoute: AuthHabitToDosRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
